import { NextResponse } from 'next/server'
import { getPayload } from 'payload'
import config from '@payload-config'

// Seed data embedded directly
const seedData = {
  categories: [
    { name: "Social Media & Wideo", slug: "social-media-wideo", icon: "Video", displayOrder: 1 },
    { name: "Produktywność & Email", slug: "produktywnosc-email", icon: "Mail", displayOrder: 2 },
    { name: "Content Marketing", slug: "content-marketing", icon: "FileText", displayOrder: 3 },
    { name: "Obsługa Klienta & CRM", slug: "obsuga-klienta-crm", icon: "Headphones", displayOrder: 4 },
    { name: "Lead Generation & Sprzedaż", slug: "lead-generation-sprzedaz", icon: "Target", displayOrder: 5 },
    { name: "E-commerce", slug: "e-commerce", icon: "ShoppingCart", displayOrder: 6 },
    { name: "Analityka & Research", slug: "analityka-research", icon: "BarChart3", displayOrder: 7 },
    { name: "HR & Rekrutacja", slug: "hr-rekrutacja", icon: "Users", displayOrder: 8 },
    { name: "Zarządzanie Treścią", slug: "zarzadzanie-trescia", icon: "FolderOpen", displayOrder: 9 },
    { name: "Finanse & Analityka", slug: "finanse-analityka", icon: "Wallet", displayOrder: 10 },
    { name: "Marketing & Analityka", slug: "marketing-analityka", icon: "TrendingUp", displayOrder: 11 },
    { name: "Grafika & Design", slug: "grafika-design", icon: "Palette", displayOrder: 12 },
    { name: "IT & DevOps", slug: "it-devops", icon: "Terminal", displayOrder: 13 },
  ],
  automations: [
    { lp: 1, name: "Klonowanie wiralowych TikToków z awatarami AI + autopublikacja na 9 platform", categorySlug: "social-media-wideo", integrations: "HTTP/Webhook, Sheets, Telegram, Google, AI", descriptionTechnical: "Automatyczne tworzenie kopii popularnych TikToków z użyciem awatarów AI i publikacja na 9 różnych platformach społecznościowych", descriptionMarketing: "Wykorzystaj siłę wiralowych trendów! AI odtwarza popularne TikToki z Twoją twarzą cyfrową i automatycznie publikuje na wszystkich platformach. Bądź wszędzie jednocześnie.", savingsMin: 8, savingsMax: 12, automationPercent: 75 },
    { lp: 2, name: "Generowanie i autopublikacja wideo na platformy z GPT-4 i Kling AI", categorySlug: "social-media-wideo", integrations: "HTTP/Webhook, Sheets, Telegram, Google, AI", descriptionTechnical: "Generowanie filmów społecznościowych za pomocą GPT-4 i Kling AI, automatyczna publikacja na wiele platform", descriptionMarketing: "Twórz profesjonalne wideo bez kamery! AI generuje angażujące filmy i publikuje je automatycznie. Od pomysłu do publikacji w minuty.", savingsMin: 6, savingsMax: 10, automationPercent: 75 },
    { lp: 3, name: "System automatycznego tworzenia i publikacji shortów z AI", categorySlug: "social-media-wideo", integrations: "HTTP/Webhook, Sheets, Telegram, Google, AI", descriptionTechnical: "Pełny przepływ pracy od tworzenia treści po publikację krótkich filmów na różnych platformach", descriptionMarketing: "Shorty to przyszłość marketingu. Nasz system tworzy je automatycznie i publikuje na YouTube, TikTok i Instagram. Zero wysiłku, maksymalny zasięg.", savingsMin: 5, savingsMax: 8, automationPercent: 75 },
    { lp: 4, name: "Tworzenie i publikacja materiałów wideo na social media (Opus Clip)", categorySlug: "social-media-wideo", integrations: "HTTP/Webhook, Sheets, AI", descriptionTechnical: "Tworzenie i publikacja treści wideo przy użyciu narzędzia Opus Clip z automatycznym udostępnianiem w mediach społecznościowych", descriptionMarketing: "Z jednego długiego wideo zrób dziesiątki klipów! AI wybiera najlepsze momenty i formatuje je idealnie pod każdą platformę.", savingsMin: 4, savingsMax: 6, automationPercent: 75 },
    { lp: 5, name: "Automatyzacja pobierania i edycji wiralowych treści z Twittera/X", categorySlug: "social-media-wideo", integrations: "HTTP/Webhook, Sheets, AI", descriptionTechnical: "Automatyczne pobieranie najpopularniejszych tweetów i ich przekształcanie w treści do ponownego wykorzystania", descriptionMarketing: "Trendy z X/Twitter automatycznie zamieniane w Twoje posty. Bądź pierwszy z najgorętszymi tematami bez śledzenia social mediów.", savingsMin: 3, savingsMax: 5, automationPercent: 75 },
    { lp: 6, name: "Automatyzacja transkrypcji i podsumowań spotkań z Notatek Google", categorySlug: "produktywnosc-email", integrations: "HTTP/Webhook, Sheets, Google, AI", descriptionTechnical: "Integracja transkrypcji spotkań z automatycznym generowaniem streszczeń za pomocą AI", descriptionMarketing: "Koniec z ręcznym spisywaniem notatek! AI transkrybuje spotkania i tworzy gotowe podsumowania z action pointami.", savingsMin: 3, savingsMax: 5, automationPercent: 75 },
    { lp: 7, name: "System automatycznego tłumaczenia i lokalizacji dokumentów (99 języków)", categorySlug: "produktywnosc-email", integrations: "HTTP/Webhook, Sheets, Google, AI", descriptionTechnical: "Tłumaczenie dokumentów na 99 języków z zachowaniem formatowania i kontekstu", descriptionMarketing: "Jeden dokument, 99 języków, zero tłumaczy. AI lokalizuje Twoje materiały zachowując niuanse i formatowanie.", savingsMin: 4, savingsMax: 8, automationPercent: 75 },
    { lp: 8, name: "Automatyczny agent e-mail (AI pierwszy kontakt i kategoryzacja)", categorySlug: "produktywnosc-email", integrations: "HTTP/Webhook, Sheets, Google, AI", descriptionTechnical: "Automatyczna obsługa pierwszego kontaktu e-mailowego, kategoryzacja i priorytetyzacja wiadomości", descriptionMarketing: "AI odpowiada na e-maile w sekundy, kategoryzuje sprawy i eskaluje tylko te ważne. Twoja skrzynka odbiorcza w końcu pod kontrolą.", savingsMin: 5, savingsMax: 10, automationPercent: 75 },
    { lp: 9, name: "Automatyzacja zarządzania zadaniami email → Asana/Notion", categorySlug: "produktywnosc-email", integrations: "HTTP/Webhook, Sheets, Google, Notion, Asana, AI", descriptionTechnical: "Przekształcanie wiadomości e-mail w zadania w systemach zarządzania projektami", descriptionMarketing: "E-mail z zadaniem? Automatycznie ląduje w Asanie lub Notion z tagami, deadline'ami i przypisaniem. Nigdy nie zgubisz zadania.", savingsMin: 2, savingsMax: 4, automationPercent: 75 },
    { lp: 10, name: "System automatycznego generowania odpowiedzi na e-maile z AI", categorySlug: "produktywnosc-email", integrations: "HTTP/Webhook, Sheets, Google, AI", descriptionTechnical: "Generowanie sugerowanych odpowiedzi na e-maile z użyciem sztucznej inteligencji", descriptionMarketing: "AI czyta e-maile i przygotowuje odpowiedzi w Twoim stylu. Jedno kliknięcie i wysłane. 10x szybsza komunikacja.", savingsMin: 3, savingsMax: 6, automationPercent: 75 },
    { lp: 11, name: "Zarządzanie kampaniami mailingowymi z personalizacją AI", categorySlug: "produktywnosc-email", integrations: "HTTP/Webhook, Sheets, Google, AI", descriptionTechnical: "Automatyczne zarządzanie kampaniami e-mail z dynamiczną personalizacją treści", descriptionMarketing: "Każdy odbiorca dostaje spersonalizowany e-mail. AI dostosowuje treść, ton i ofertę. Masowość z indywidualnym podejściem.", savingsMin: 4, savingsMax: 7, automationPercent: 75 },
    { lp: 12, name: "AI-powered system priorytetyzacji skrzynki odbiorczej", categorySlug: "produktywnosc-email", integrations: "HTTP/Webhook, Sheets, Google, AI", descriptionTechnical: "Inteligentne sortowanie i priorytetyzacja wiadomości e-mail", descriptionMarketing: "AI wie co jest ważne! Sortuje Twoją skrzynkę, wyciąga pilne sprawy na górę i ukrywa spam. Poranna kawa bez stresu.", savingsMin: 2, savingsMax: 4, automationPercent: 75 },
    { lp: 13, name: "Automatyzacja follow-upów z inteligentnymi przypomnieniami", categorySlug: "produktywnosc-email", integrations: "HTTP/Webhook, Sheets, Google, AI", descriptionTechnical: "System automatycznych przypomnień i follow-upów z personalizacją", descriptionMarketing: "Koniec z zapomnianymi follow-upami! AI śledzi konwersacje i wysyła przypomnienia w idealnym momencie. Zamykaj więcej deali.", savingsMin: 2, savingsMax: 4, automationPercent: 75 },
    { lp: 14, name: "System generowania i zarządzania podpisami e-mail", categorySlug: "produktywnosc-email", integrations: "HTTP/Webhook, Sheets, Google", descriptionTechnical: "Centralne zarządzanie i automatyczna aktualizacja podpisów e-mail w organizacji", descriptionMarketing: "Jednolite podpisy e-mail w całej firmie. Zmiana telefonu? Aktualizacja promocji? Jedno kliknięcie zmienia wszystko.", savingsMin: 1, savingsMax: 2, automationPercent: 75 },
    { lp: 15, name: "Automatyczne tworzenie artykułów z badaniami SEO", categorySlug: "content-marketing", integrations: "HTTP/Webhook, Sheets, Wordpress, AI", descriptionTechnical: "Generowanie artykułów blogowych z automatyczną optymalizacją SEO i publikacją", descriptionMarketing: "AI pisze artykuły zoptymalizowane pod SEO. Research, pisanie, optymalizacja - wszystko automatycznie. Blog rośnie sam.", savingsMin: 5, savingsMax: 8, automationPercent: 75 },
    { lp: 16, name: "System automatycznego content planu z AI", categorySlug: "content-marketing", integrations: "HTTP/Webhook, Sheets, Google, AI", descriptionTechnical: "Generowanie miesięcznych planów contentu z uwzględnieniem trendów i analityki", descriptionMarketing: "AI analizuje trendy i planuje content na miesiąc do przodu. Kalendarz publikacji wypełnia się sam z gotowymi tematami.", savingsMin: 3, savingsMax: 5, automationPercent: 75 },
    { lp: 17, name: "Automatyczny system pisania i publikacji na LinkedIn", categorySlug: "content-marketing", integrations: "HTTP/Webhook, Sheets, LinkedIn, AI", descriptionTechnical: "Generowanie i publikacja profesjonalnych postów na LinkedIn", descriptionMarketing: "LinkedIn wymaga regularności. AI pisze posty w Twoim stylu eksperta i publikuje je optymalnie. Buduj personal brand automatycznie.", savingsMin: 3, savingsMax: 5, automationPercent: 75 },
    { lp: 18, name: "Automatyzacja badań rynku i tworzenia raportów", categorySlug: "content-marketing", integrations: "HTTP/Webhook, Sheets, Google, AI", descriptionTechnical: "Automatyczne zbieranie danych rynkowych i generowanie szczegółowych raportów", descriptionMarketing: "Raporty rynkowe w minuty zamiast dni. AI zbiera dane, analizuje konkurencję i tworzy profesjonalne dokumenty.", savingsMin: 6, savingsMax: 12, automationPercent: 75 },
    { lp: 19, name: "System ponownego wykorzystania treści (repurposing)", categorySlug: "content-marketing", integrations: "HTTP/Webhook, Sheets, AI", descriptionTechnical: "Przekształcanie jednego formatu treści w wiele innych automatycznie", descriptionMarketing: "Jeden artykuł = 10 postów, 3 wideo, 1 podcast. AI przekształca Twój content we wszystkie formaty automatycznie.", savingsMin: 4, savingsMax: 6, automationPercent: 75 },
    { lp: 20, name: "Automatyczny system generowania infografik", categorySlug: "content-marketing", integrations: "HTTP/Webhook, Sheets, Canva, AI", descriptionTechnical: "Tworzenie infografik na podstawie danych i tekstów źródłowych", descriptionMarketing: "Dane zamieniają się w piękne infografiki. AI projektuje, dobiera kolory i eksportuje gotowe do publikacji grafiki.", savingsMin: 3, savingsMax: 5, automationPercent: 75 },
    { lp: 21, name: "AI-powered system pisania case studies", categorySlug: "content-marketing", integrations: "HTTP/Webhook, Sheets, Google, AI", descriptionTechnical: "Automatyczne tworzenie case studies na podstawie danych projektowych", descriptionMarketing: "Case studies sprzedają, ale kto ma czas je pisać? AI zbiera dane z projektu i tworzy przekonujące historie sukcesu.", savingsMin: 4, savingsMax: 6, automationPercent: 75 },
    { lp: 22, name: "Automatyzacja tworzenia white papers i e-booków", categorySlug: "content-marketing", integrations: "HTTP/Webhook, Sheets, Google, AI", descriptionTechnical: "Generowanie długich form contentowych z automatycznym formatowaniem", descriptionMarketing: "E-booki generują leady. AI pisze je za Ciebie - od researchu po końcowy PDF. Lead magnety na żądanie.", savingsMin: 8, savingsMax: 15, automationPercent: 75 },
    { lp: 23, name: "System monitoringu i reagowania na wzmianki o marce", categorySlug: "content-marketing", integrations: "HTTP/Webhook, Sheets, Slack, AI", descriptionTechnical: "Śledzenie wzmianek o marce w internecie z automatycznymi powiadomieniami", descriptionMarketing: "Ktoś mówi o Twojej marce? Wiesz o tym natychmiast! AI monitoruje internet i przygotowuje odpowiedzi.", savingsMin: 2, savingsMax: 4, automationPercent: 75 },
    { lp: 24, name: "Automatyzacja zbierania i moderacji opinii klientów", categorySlug: "obsuga-klienta-crm", integrations: "HTTP/Webhook, Sheets, Google, AI", descriptionTechnical: "Automatyczne zbieranie, kategoryzacja i odpowiadanie na opinie klientów", descriptionMarketing: "Opinie budują zaufanie. AI zbiera je automatycznie, odpowiada na negatywne i eksponuje pozytywne.", savingsMin: 3, savingsMax: 5, automationPercent: 75 },
    { lp: 25, name: "AI Chatbot dla obsługi klienta (24/7)", categorySlug: "obsuga-klienta-crm", integrations: "HTTP/Webhook, Sheets, AI", descriptionTechnical: "Inteligentny chatbot odpowiadający na pytania klientów przez całą dobę", descriptionMarketing: "Obsługa klienta 24/7 bez nocnych zmian. AI odpowiada na 80% pytań natychmiast i eskaluje tylko trudne sprawy.", savingsMin: 10, savingsMax: 20, automationPercent: 75 },
    { lp: 26, name: "System automatycznej segmentacji i oceny leadów", categorySlug: "obsuga-klienta-crm", integrations: "HTTP/Webhook, Sheets, CRM, AI", descriptionTechnical: "Automatyczne przydzielanie leadów do segmentów i ocena ich wartości", descriptionMarketing: "AI ocenia każdego leada i przydziela do handlowca idealnie dopasowanego. Gorące leady na górze, zimne do nurturingu.", savingsMin: 3, savingsMax: 6, automationPercent: 75 },
    { lp: 27, name: "Automatyzacja ankiet satysfakcji i NPS", categorySlug: "obsuga-klienta-crm", integrations: "HTTP/Webhook, Sheets, Google, AI", descriptionTechnical: "Automatyczne wysyłanie i analiza ankiet satysfakcji klientów", descriptionMarketing: "NPS i CSAT mierzone automatycznie. AI wysyła ankiety w idealnym momencie i analizuje wyniki w czasie rzeczywistym.", savingsMin: 2, savingsMax: 4, automationPercent: 75 },
    { lp: 28, name: "System automatycznego uzupełniania danych w CRM", categorySlug: "obsuga-klienta-crm", integrations: "HTTP/Webhook, Sheets, CRM, AI", descriptionTechnical: "Wzbogacanie danych kontaktowych o informacje z zewnętrznych źródeł", descriptionMarketing: "CRM sam się uzupełnia! AI znajduje brakujące dane: stanowiska, firmy, social media. Kompletne profile bez ręcznej pracy.", savingsMin: 3, savingsMax: 5, automationPercent: 75 },
    { lp: 29, name: "Automatyzacja powiadomień o ważnych wydarzeniach klienta", categorySlug: "obsuga-klienta-crm", integrations: "HTTP/Webhook, Sheets, CRM, Slack", descriptionTechnical: "Automatyczne powiadomienia o urodzinach, rocznicach współpracy i innych kluczowych datach", descriptionMarketing: "Nigdy nie zapomnij o urodzinach klienta! System przypomina o ważnych datach i sugeruje personalizowane życzenia.", savingsMin: 1, savingsMax: 2, automationPercent: 75 },
    { lp: 30, name: "System automatycznego raportowania aktywności handlowców", categorySlug: "obsuga-klienta-crm", integrations: "HTTP/Webhook, Sheets, CRM, AI", descriptionTechnical: "Generowanie raportów aktywności zespołu sprzedażowego bez manualnego wprowadzania danych", descriptionMarketing: "Raporty sprzedażowe generują się same. AI zbiera dane z CRM, e-maili i kalendarzy. Przejrzyste dashboardy codziennie rano.", savingsMin: 3, savingsMax: 5, automationPercent: 75 },
    { lp: 31, name: "Automatyzacja generowania leadów z LinkedIn", categorySlug: "lead-generation-sprzedaz", integrations: "HTTP/Webhook, Sheets, LinkedIn, AI", descriptionTechnical: "Automatyczne wyszukiwanie i kontaktowanie potencjalnych klientów na LinkedIn", descriptionMarketing: "LinkedIn to kopalnia leadów. AI znajduje idealnych prospects, personalizuje wiadomości i nawiązuje kontakt automatycznie.", savingsMin: 5, savingsMax: 10, automationPercent: 75 },
    { lp: 32, name: "System automatycznego cold mailingu z personalizacją AI", categorySlug: "lead-generation-sprzedaz", integrations: "HTTP/Webhook, Sheets, Google, AI", descriptionTechnical: "Wysyłanie spersonalizowanych cold maili z automatycznym follow-upem", descriptionMarketing: "Cold mailing który działa! AI personalizuje każdy mail, śledzi otwarcia i wysyła follow-upy w idealnym momencie.", savingsMin: 4, savingsMax: 8, automationPercent: 75 },
    { lp: 33, name: "Automatyzacja kwalifikacji leadów z formularzy", categorySlug: "lead-generation-sprzedaz", integrations: "HTTP/Webhook, Sheets, CRM, AI", descriptionTechnical: "Automatyczna ocena i kategoryzacja leadów przychodzących z formularzy", descriptionMarketing: "Formularz wypełniony = lead oceniony. AI sprawdza fit, przydziela score i kieruje do właściwego handlowca.", savingsMin: 2, savingsMax: 4, automationPercent: 75 },
    { lp: 34, name: "System automatycznego umawiania spotkań handlowych", categorySlug: "lead-generation-sprzedaz", integrations: "HTTP/Webhook, Calendly, Google, AI", descriptionTechnical: "Automatyzacja procesu umawiania i przypominania o spotkaniach", descriptionMarketing: "Koniec z ping-pongiem mailowym! AI proponuje terminy, rezerwuje kalendarze i wysyła przypomnienia.", savingsMin: 2, savingsMax: 4, automationPercent: 75 },
    { lp: 35, name: "Automatyzacja tworzenia ofert i propozycji handlowych", categorySlug: "lead-generation-sprzedaz", integrations: "HTTP/Webhook, Sheets, Google, AI", descriptionTechnical: "Generowanie spersonalizowanych ofert na podstawie danych z CRM", descriptionMarketing: "Oferty w minuty zamiast godzin. AI pobiera dane klienta i generuje profesjonalną propozycję z cenami i warunkami.", savingsMin: 3, savingsMax: 6, automationPercent: 75 },
    { lp: 36, name: "System scoringu i priorytetyzacji szans sprzedażowych", categorySlug: "lead-generation-sprzedaz", integrations: "HTTP/Webhook, Sheets, CRM, AI", descriptionTechnical: "Automatyczna ocena prawdopodobieństwa zamknięcia szans sprzedażowych", descriptionMarketing: "AI wie które deale zamkniesz. Skup się na szansach z najwyższym prawdopodobieństwem sukcesu.", savingsMin: 2, savingsMax: 4, automationPercent: 75 },
    { lp: 37, name: "Automatyzacja synchronizacji danych między platformami e-commerce", categorySlug: "e-commerce", integrations: "HTTP/Webhook, Sheets, Shopify, WooCommerce", descriptionTechnical: "Synchronizacja produktów, zamówień i stanów magazynowych między platformami", descriptionMarketing: "Sprzedajesz na wielu platformach? Stany magazynowe, ceny i produkty synchronizują się automatycznie.", savingsMin: 4, savingsMax: 8, automationPercent: 75 },
    { lp: 38, name: "System automatycznego zarządzania cenami i promocjami", categorySlug: "e-commerce", integrations: "HTTP/Webhook, Sheets, Shopify, AI", descriptionTechnical: "Dynamiczne dostosowywanie cen na podstawie konkurencji i popytu", descriptionMarketing: "Ceny optymalizowane automatycznie! AI śledzi konkurencję i popyt, dostosowując ceny dla maksymalnego zysku.", savingsMin: 3, savingsMax: 6, automationPercent: 75 },
    { lp: 39, name: "Automatyzacja obsługi zwrotów i reklamacji", categorySlug: "e-commerce", integrations: "HTTP/Webhook, Sheets, Shopify, AI", descriptionTechnical: "Automatyczna obsługa procesu zwrotów z generowaniem etykiet i komunikacją", descriptionMarketing: "Zwroty bez bólu głowy. System generuje etykiety, komunikuje się z klientem i aktualizuje stany.", savingsMin: 3, savingsMax: 5, automationPercent: 75 },
    { lp: 40, name: "System automatycznego generowania opisów produktów SEO", categorySlug: "e-commerce", integrations: "HTTP/Webhook, Sheets, Shopify, AI", descriptionTechnical: "Tworzenie zoptymalizowanych opisów produktów z użyciem AI", descriptionMarketing: "1000 produktów do opisania? AI generuje unikalne, SEO-friendly opisy w Twoim stylu marki.", savingsMin: 5, savingsMax: 10, automationPercent: 75 },
    { lp: 41, name: "Automatyzacja remarketingu porzuconych koszyków", categorySlug: "e-commerce", integrations: "HTTP/Webhook, Sheets, Shopify, AI", descriptionTechnical: "Automatyczne sekwencje odzyskiwania porzuconych koszyków", descriptionMarketing: "70% koszyków porzuconych to utracona sprzedaż. AI odzyskuje je serią personalizowanych wiadomości.", savingsMin: 2, savingsMax: 4, automationPercent: 75 },
    { lp: 42, name: "System automatycznego zarządzania opiniami produktów", categorySlug: "e-commerce", integrations: "HTTP/Webhook, Sheets, Shopify, AI", descriptionTechnical: "Zbieranie, moderacja i odpowiadanie na opinie produktowe", descriptionMarketing: "Opinie sprzedają! AI prosi o recenzje, moderuje je i odpowiada na negatywne zanim zaszkodzą.", savingsMin: 2, savingsMax: 4, automationPercent: 75 },
    { lp: 43, name: "Automatyzacja powiadomień o dostępności produktów", categorySlug: "e-commerce", integrations: "HTTP/Webhook, Sheets, Shopify", descriptionTechnical: "Automatyczne powiadomienia klientów o ponownej dostępności produktów", descriptionMarketing: "Produkt wrócił na magazyn? Klienci dowiadują się pierwsi. Automatyczne powiadomienia = szybka sprzedaż.", savingsMin: 1, savingsMax: 2, automationPercent: 75 },
    { lp: 44, name: "System automatycznego raportowania sprzedaży", categorySlug: "e-commerce", integrations: "HTTP/Webhook, Sheets, Shopify, AI", descriptionTechnical: "Generowanie codziennych, tygodniowych i miesięcznych raportów sprzedażowych", descriptionMarketing: "Raporty sprzedażowe codziennie rano w skrzynce. Trendy, bestsellery, problemy - wszystko jasne od pierwszego spojrzenia.", savingsMin: 2, savingsMax: 4, automationPercent: 75 },
    { lp: 45, name: "Automatyczny web scraping i monitorowanie konkurencji", categorySlug: "analityka-research", integrations: "HTTP/Webhook, Sheets, AI", descriptionTechnical: "Automatyczne zbieranie danych o konkurencji ze stron internetowych", descriptionMarketing: "Śledź konkurencję automatycznie. Ceny, produkty, promocje - wszystko w jednym dashboardzie aktualizowanym co godzinę.", savingsMin: 4, savingsMax: 8, automationPercent: 75 },
    { lp: 46, name: "System automatycznego monitorowania cen konkurencji", categorySlug: "analityka-research", integrations: "HTTP/Webhook, Sheets, AI", descriptionTechnical: "Śledzenie zmian cen u konkurencji z alertami", descriptionMarketing: "Konkurencja obniżyła cenę? Wiesz o tym natychmiast. Automatyczne alerty i sugestie reakcji.", savingsMin: 3, savingsMax: 5, automationPercent: 75 },
    { lp: 47, name: "Automatyzacja analizy sentymentu w social media", categorySlug: "analityka-research", integrations: "HTTP/Webhook, Sheets, AI", descriptionTechnical: "Analiza nastrojów i opinii o marce w mediach społecznościowych", descriptionMarketing: "Co ludzie myślą o Twojej marce? AI analizuje tysiące postów i komentarzy, pokazując prawdziwy sentyment.", savingsMin: 3, savingsMax: 6, automationPercent: 75 },
    { lp: 48, name: "System automatycznego zbierania danych z formularzy i ankiet", categorySlug: "analityka-research", integrations: "HTTP/Webhook, Sheets, Google, AI", descriptionTechnical: "Agregacja i analiza odpowiedzi z różnych formularzy i ankiet", descriptionMarketing: "Dane z ankiet analizowane automatycznie. Trendy, insights i rekomendacje bez ręcznego przekopywania arkuszy.", savingsMin: 2, savingsMax: 4, automationPercent: 75 },
    { lp: 49, name: "Automatyzacja generowania raportów analitycznych", categorySlug: "analityka-research", integrations: "HTTP/Webhook, Sheets, Google Analytics, AI", descriptionTechnical: "Tworzenie regularnych raportów z danych analitycznych", descriptionMarketing: "Raporty GA4 generują się same. Insights, trendy i rekomendacje w czytelnym formacie co tydzień.", savingsMin: 3, savingsMax: 6, automationPercent: 75 },
    { lp: 50, name: "System automatycznego śledzenia KPI i alertów", categorySlug: "analityka-research", integrations: "HTTP/Webhook, Sheets, Slack, AI", descriptionTechnical: "Monitorowanie kluczowych wskaźników z automatycznymi powiadomieniami", descriptionMarketing: "KPI spadają? Wiesz o tym natychmiast. Automatyczne alerty gdy wskaźniki przekraczają progi.", savingsMin: 2, savingsMax: 4, automationPercent: 75 },
    { lp: 51, name: "Automatyzacja publikacji ofert pracy na wielu portalach", categorySlug: "hr-rekrutacja", integrations: "HTTP/Webhook, Sheets, LinkedIn, Indeed", descriptionTechnical: "Jednoczesna publikacja ofert pracy na wszystkich głównych portalach", descriptionMarketing: "Jedna oferta, 10 portali. AI publikuje i monitoruje wszystkie ogłoszenia z jednego miejsca.", savingsMin: 2, savingsMax: 4, automationPercent: 75 },
    { lp: 52, name: "System automatycznej preselekcji CV z AI", categorySlug: "hr-rekrutacja", integrations: "HTTP/Webhook, Sheets, AI", descriptionTechnical: "Automatyczna analiza i scoring CV pod kątem dopasowania do stanowiska", descriptionMarketing: "100 CV? AI przeczyta je wszystkie i wyłoni top 10 najlepszych kandydatów. Zero stronniczości, same fakty.", savingsMin: 5, savingsMax: 10, automationPercent: 75 },
    { lp: 53, name: "Automatyzacja umawiania i przypominania o rozmowach rekrutacyjnych", categorySlug: "hr-rekrutacja", integrations: "HTTP/Webhook, Calendly, Google, AI", descriptionTechnical: "Automatyczne umawianie rozmów i wysyłanie przypomnień kandydatom", descriptionMarketing: "Koniec z ręcznym umawianiem rozmów. System proponuje terminy, rezerwuje sale i wysyła przypomnienia.", savingsMin: 2, savingsMax: 4, automationPercent: 75 },
    { lp: 54, name: "System automatycznego onboardingu nowych pracowników", categorySlug: "hr-rekrutacja", integrations: "HTTP/Webhook, Sheets, Slack, Notion", descriptionTechnical: "Automatyzacja procesu wdrażania nowych pracowników z checklistami i zadaniami", descriptionMarketing: "Nowy pracownik = gotowy plan wdrożenia. System przydziela zadania, materiały i mentora automatycznie.", savingsMin: 4, savingsMax: 8, automationPercent: 75 },
    { lp: 55, name: "Automatyzacja zbierania i analizy feedbacku pracowniczego", categorySlug: "hr-rekrutacja", integrations: "HTTP/Webhook, Sheets, Google, AI", descriptionTechnical: "Regularne zbieranie opinii pracowników z automatyczną analizą", descriptionMarketing: "Pulse check zespołu co tydzień. AI zbiera feedback anonimowo i pokazuje trendy nastrojów.", savingsMin: 2, savingsMax: 4, automationPercent: 75 },
    { lp: 56, name: "System automatycznego raportowania czasu pracy", categorySlug: "hr-rekrutacja", integrations: "HTTP/Webhook, Sheets, Clockify, AI", descriptionTechnical: "Agregacja i analiza danych o czasie pracy z różnych źródeł", descriptionMarketing: "Raporty RCP generują się same. Integracja z systemami śledzenia czasu i automatyczne zestawienia.", savingsMin: 2, savingsMax: 4, automationPercent: 75 },
    { lp: 57, name: "Automatyzacja procesu offboardingu pracowników", categorySlug: "hr-rekrutacja", integrations: "HTTP/Webhook, Sheets, Slack, Google", descriptionTechnical: "Automatyczna obsługa procesu odejścia pracownika z checklistami", descriptionMarketing: "Pracownik odchodzi? System pilnuje zwrotu sprzętu, przekazania obowiązków i exit interview.", savingsMin: 2, savingsMax: 4, automationPercent: 75 },
    { lp: 58, name: "Automatyczny system zarządzania bazą wiedzy firmowej", categorySlug: "zarzadzanie-trescia", integrations: "HTTP/Webhook, Sheets, Notion, AI", descriptionTechnical: "Automatyczne kategoryzowanie, aktualizowanie i indeksowanie wiedzy firmowej", descriptionMarketing: "Wiedza firmowa zorganizowana jak Netflix. AI taguje, kategoryzuje i aktualizuje dokumenty automatycznie.", savingsMin: 3, savingsMax: 6, automationPercent: 75 },
    { lp: 59, name: "System automatycznego tworzenia dokumentacji technicznej", categorySlug: "zarzadzanie-trescia", integrations: "HTTP/Webhook, Sheets, GitHub, AI", descriptionTechnical: "Generowanie dokumentacji technicznej na podstawie kodu i komentarzy", descriptionMarketing: "Dokumentacja pisana sama! AI analizuje kod i tworzy czytelną dokumentację dla developerów.", savingsMin: 4, savingsMax: 8, automationPercent: 75 },
    { lp: 60, name: "Automatyzacja archiwizacji i organizacji dokumentów", categorySlug: "zarzadzanie-trescia", integrations: "HTTP/Webhook, Sheets, Google Drive, AI", descriptionTechnical: "Automatyczne sortowanie, tagowanie i archiwizacja dokumentów", descriptionMarketing: "Dokumenty same trafiają do właściwych folderów. AI rozpoznaje typ, datę i temat, organizując archiwum.", savingsMin: 2, savingsMax: 4, automationPercent: 75 },
    { lp: 61, name: "System automatycznego wersjonowania i śledzenia zmian", categorySlug: "zarzadzanie-trescia", integrations: "HTTP/Webhook, Sheets, Google Drive, Notion", descriptionTechnical: "Automatyczne śledzenie wersji dokumentów z historią zmian", descriptionMarketing: "Nigdy nie zgub zmian w dokumentach. System śledzi każdą edycję i pozwala wrócić do dowolnej wersji.", savingsMin: 2, savingsMax: 3, automationPercent: 75 },
    { lp: 62, name: "Automatyzacja procesów zatwierdzania dokumentów", categorySlug: "zarzadzanie-trescia", integrations: "HTTP/Webhook, Sheets, Slack, Google", descriptionTechnical: "Automatyczne workflow zatwierdzania z powiadomieniami i eskalacją", descriptionMarketing: "Dokumenty do zatwierdzenia? System wysyła do właściwych osób, śledzi status i przypomina.", savingsMin: 2, savingsMax: 4, automationPercent: 75 },
    { lp: 63, name: "System automatycznego generowania umów i dokumentów", categorySlug: "zarzadzanie-trescia", integrations: "HTTP/Webhook, Sheets, Google, AI", descriptionTechnical: "Tworzenie dokumentów z szablonów z automatycznym wypełnianiem danych", descriptionMarketing: "Umowy generują się same! Dane z CRM trafiają do szablonu i dokument jest gotowy do podpisu.", savingsMin: 3, savingsMax: 6, automationPercent: 75 },
    { lp: 64, name: "Automatyzacja ekstrakcji danych z dokumentów PDF/skanów", categorySlug: "zarzadzanie-trescia", integrations: "HTTP/Webhook, Sheets, AI", descriptionTechnical: "Automatyczne wyciąganie danych z dokumentów za pomocą OCR i AI", descriptionMarketing: "Faktury, umowy, rachunki - AI wyciąga dane i wprowadza do systemu. Koniec z ręcznym przepisywaniem.", savingsMin: 4, savingsMax: 8, automationPercent: 75 },
    { lp: 65, name: "Automatyzacja procesowania faktur i rachunków", categorySlug: "finanse-analityka", integrations: "HTTP/Webhook, Sheets, Xero, AI", descriptionTechnical: "Automatyczne przetwarzanie, kategoryzacja i księgowanie faktur", descriptionMarketing: "Faktury przetwarzane automatycznie. AI czyta, kategoryzuje i wprowadza do systemu księgowego.", savingsMin: 5, savingsMax: 10, automationPercent: 75 },
    { lp: 66, name: "System automatycznych przypomnień o płatnościach", categorySlug: "finanse-analityka", integrations: "HTTP/Webhook, Sheets, Google, AI", descriptionTechnical: "Automatyczne przypomnienia o zbliżających się i zaległych płatnościach", descriptionMarketing: "Koniec z przeterminowanymi fakturami! System wysyła przypomnienia przed terminem i monituje po.", savingsMin: 2, savingsMax: 4, automationPercent: 75 },
    { lp: 67, name: "Automatyzacja raportowania finansowego", categorySlug: "finanse-analityka", integrations: "HTTP/Webhook, Sheets, Xero, AI", descriptionTechnical: "Generowanie regularnych raportów finansowych z różnych źródeł", descriptionMarketing: "Raporty finansowe codziennie rano. Cash flow, P&L, bilans - wszystko aktualne i czytelne.", savingsMin: 4, savingsMax: 8, automationPercent: 75 },
    { lp: 68, name: "System automatycznej reconcyliacji transakcji", categorySlug: "finanse-analityka", integrations: "HTTP/Webhook, Sheets, Bank API, AI", descriptionTechnical: "Automatyczne uzgadnianie transakcji bankowych z systemem księgowym", descriptionMarketing: "Reconcyliacja która robi się sama. AI dopasowuje transakcje bankowe do faktur i raportuje rozbieżności.", savingsMin: 3, savingsMax: 6, automationPercent: 75 },
    { lp: 69, name: "Automatyzacja tworzenia budżetów i prognoz", categorySlug: "finanse-analityka", integrations: "HTTP/Webhook, Sheets, AI", descriptionTechnical: "Generowanie budżetów i prognoz finansowych na podstawie danych historycznych", descriptionMarketing: "Budżety oparte na danych. AI analizuje historię i tworzy realistyczne prognozy finansowe.", savingsMin: 4, savingsMax: 8, automationPercent: 75 },
    { lp: 70, name: "System automatycznego śledzenia wydatków", categorySlug: "finanse-analityka", integrations: "HTTP/Webhook, Sheets, Bank API, AI", descriptionTechnical: "Automatyczna kategoryzacja i analiza wydatków firmowych", descriptionMarketing: "Wszystkie wydatki pod kontrolą. AI kategoryzuje, analizuje i alarmuje o anomaliach.", savingsMin: 2, savingsMax: 4, automationPercent: 75 },
    { lp: 71, name: "Automatyzacja rozliczania podróży służbowych", categorySlug: "finanse-analityka", integrations: "HTTP/Webhook, Sheets, Google, AI", descriptionTechnical: "Automatyczne przetwarzanie i rozliczanie kosztów podróży", descriptionMarketing: "Delegacje rozliczane automatycznie. Pracownik dodaje paragony, AI wypełnia formularz i wysyła do zatwierdzenia.", savingsMin: 2, savingsMax: 4, automationPercent: 75 },
    { lp: 72, name: "System automatycznego raportowania ROI kampanii", categorySlug: "marketing-analityka", integrations: "HTTP/Webhook, Sheets, Google Analytics, AI", descriptionTechnical: "Automatyczne obliczanie i raportowanie zwrotu z inwestycji marketingowych", descriptionMarketing: "ROI każdej kampanii obliczany automatycznie. Widzisz co działa i gdzie ciąć koszty.", savingsMin: 3, savingsMax: 6, automationPercent: 75 },
    { lp: 73, name: "Automatyzacja zbierania danych z wielu platform reklamowych", categorySlug: "marketing-analityka", integrations: "HTTP/Webhook, Sheets, Google Ads, Meta Ads, AI", descriptionTechnical: "Agregacja danych z Google Ads, Meta Ads, LinkedIn Ads w jednym miejscu", descriptionMarketing: "Wszystkie platformy reklamowe w jednym dashboardzie. Koniec z logowaniem do 5 różnych paneli.", savingsMin: 3, savingsMax: 5, automationPercent: 75 },
    { lp: 74, name: "System automatycznego A/B testowania kreacji", categorySlug: "marketing-analityka", integrations: "HTTP/Webhook, Sheets, Google Ads, AI", descriptionTechnical: "Automatyczne testowanie i optymalizacja kreacji reklamowych", descriptionMarketing: "Kreacje testowane automatycznie. AI zamienia słabsze warianty na mocniejsze bez Twojej interwencji.", savingsMin: 3, savingsMax: 6, automationPercent: 75 },
    { lp: 75, name: "Automatyzacja raportowania skuteczności email marketingu", categorySlug: "marketing-analityka", integrations: "HTTP/Webhook, Sheets, Mailchimp, AI", descriptionTechnical: "Automatyczne raporty z kampanii email z analizą trendów", descriptionMarketing: "Wyniki email marketingu na wyciągnięcie ręki. Open rate, CTR, konwersje - wszystko w jednym raporcie.", savingsMin: 2, savingsMax: 4, automationPercent: 75 },
    { lp: 76, name: "System automatycznego śledzenia konwersji multi-touch", categorySlug: "marketing-analityka", integrations: "HTTP/Webhook, Sheets, Google Analytics, AI", descriptionTechnical: "Zaawansowane śledzenie atrybucji konwersji z wielu punktów styku", descriptionMarketing: "Która kampania naprawdę sprzedaje? AI śledzi całą ścieżkę klienta i przypisuje zasługi właściwie.", savingsMin: 3, savingsMax: 6, automationPercent: 75 },
    { lp: 77, name: "Automatyzacja analizy kohortowej użytkowników", categorySlug: "marketing-analityka", integrations: "HTTP/Webhook, Sheets, Mixpanel, AI", descriptionTechnical: "Automatyczne generowanie analiz kohortowych z segmentacją użytkowników", descriptionMarketing: "Kohorty analizowane automatycznie. Widzisz jak różne grupy użytkowników zachowują się w czasie.", savingsMin: 3, savingsMax: 5, automationPercent: 75 },
    { lp: 78, name: "System automatycznego generowania materiałów graficznych", categorySlug: "grafika-design", integrations: "HTTP/Webhook, Sheets, Canva, AI", descriptionTechnical: "Automatyczne tworzenie grafik marketingowych z szablonów", descriptionMarketing: "1000 banerów w godzinę! AI generuje warianty grafik dla każdego produktu i formatu.", savingsMin: 5, savingsMax: 10, automationPercent: 75 },
    { lp: 79, name: "Automatyzacja adaptacji grafik do różnych formatów", categorySlug: "grafika-design", integrations: "HTTP/Webhook, Sheets, Canva, AI", descriptionTechnical: "Automatyczne skalowanie i dostosowywanie grafik do wymagań platform", descriptionMarketing: "Jedna grafika, 20 formatów. AI dostosowuje rozmiary do każdej platformy automatycznie.", savingsMin: 3, savingsMax: 6, automationPercent: 75 },
    { lp: 80, name: "System automatycznego brandingu materiałów", categorySlug: "grafika-design", integrations: "HTTP/Webhook, Sheets, Canva, AI", descriptionTechnical: "Automatyczne nakładanie elementów brandowych na materiały", descriptionMarketing: "Każdy materiał w brand guidelines. AI dodaje logo, fonty i kolory zgodnie ze standardami.", savingsMin: 2, savingsMax: 4, automationPercent: 75 },
    { lp: 81, name: "Automatyzacja generowania miniatur i cover images", categorySlug: "grafika-design", integrations: "HTTP/Webhook, Sheets, Canva, AI", descriptionTechnical: "Tworzenie miniatur wideo i obrazów wyróżniających automatycznie", descriptionMarketing: "Miniatury YouTube, covery postów - AI generuje przyciągające wzrok grafiki dla każdego contentu.", savingsMin: 2, savingsMax: 4, automationPercent: 75 },
    { lp: 82, name: "System automatycznej optymalizacji obrazów dla web", categorySlug: "grafika-design", integrations: "HTTP/Webhook, Cloudinary, AI", descriptionTechnical: "Automatyczna kompresja i optymalizacja obrazów dla różnych urządzeń", descriptionMarketing: "Strona ładuje się szybciej! AI optymalizuje obrazy zachowując jakość i redukując rozmiar.", savingsMin: 2, savingsMax: 3, automationPercent: 75 },
    { lp: 83, name: "Automatyzacja monitorowania serwerów i alertów", categorySlug: "it-devops", integrations: "HTTP/Webhook, Sheets, Slack, Prometheus", descriptionTechnical: "Automatyczne monitorowanie infrastruktury z inteligentnymi alertami", descriptionMarketing: "Serwer pada? Wiesz o tym pierwszy. Automatyczne monitorowanie 24/7 z alertami na Slack.", savingsMin: 4, savingsMax: 8, automationPercent: 75 },
    { lp: 84, name: "System automatycznego backupu i weryfikacji", categorySlug: "it-devops", integrations: "HTTP/Webhook, AWS, Slack", descriptionTechnical: "Automatyczne kopie zapasowe z weryfikacją integralności", descriptionMarketing: "Backupy które działają. System tworzy kopie, weryfikuje je i alertuje o problemach.", savingsMin: 2, savingsMax: 4, automationPercent: 75 },
    { lp: 85, name: "Automatyzacja deploymentów i CI/CD", categorySlug: "it-devops", integrations: "HTTP/Webhook, GitHub, Slack, Docker", descriptionTechnical: "Automatyczne wdrożenia kodu z testami i rollbackami", descriptionMarketing: "Deploy jednym kliknięciem. Testy, wdrożenie, rollback jeśli coś nie działa - wszystko automatycznie.", savingsMin: 5, savingsMax: 10, automationPercent: 75 },
    { lp: 86, name: "System automatycznego skalowania infrastruktury", categorySlug: "it-devops", integrations: "HTTP/Webhook, AWS, Kubernetes", descriptionTechnical: "Automatyczne skalowanie zasobów w odpowiedzi na obciążenie", descriptionMarketing: "Serwery skalują się same. Ruch rośnie? Dodajemy zasoby. Spada? Redukujemy koszty.", savingsMin: 3, savingsMax: 6, automationPercent: 75 },
    { lp: 87, name: "Automatyzacja zarządzania certyfikatami SSL", categorySlug: "it-devops", integrations: "HTTP/Webhook, Let's Encrypt, Slack", descriptionTechnical: "Automatyczne odnawianie i zarządzanie certyfikatami bezpieczeństwa", descriptionMarketing: "Koniec z wygasłymi certyfikatami! System odnawia SSL automatycznie i alertuje o problemach.", savingsMin: 1, savingsMax: 2, automationPercent: 75 },
    { lp: 88, name: "System automatycznego raportowania incydentów", categorySlug: "it-devops", integrations: "HTTP/Webhook, Sheets, Slack, PagerDuty", descriptionTechnical: "Automatyczne dokumentowanie i raportowanie incydentów IT", descriptionMarketing: "Każdy incydent dokumentowany automatycznie. Post-mortemy generują się same z timeline'em i root cause.", savingsMin: 2, savingsMax: 4, automationPercent: 75 },
    { lp: 89, name: "Automatyzacja audytu bezpieczeństwa i compliance", categorySlug: "it-devops", integrations: "HTTP/Webhook, Sheets, AI", descriptionTechnical: "Automatyczne skanowanie i raportowanie zgodności z politykami bezpieczeństwa", descriptionMarketing: "Audyt bezpieczeństwa co tydzień. AI skanuje systemy i raportuje luki zanim staną się problemem.", savingsMin: 4, savingsMax: 8, automationPercent: 75 },
    { lp: 90, name: "System automatycznego zarządzania uprawnieniami", categorySlug: "it-devops", integrations: "HTTP/Webhook, Okta, Google Workspace", descriptionTechnical: "Automatyczne przydzielanie i odbieranie uprawnień w systemach", descriptionMarketing: "Nowy pracownik = gotowe konta. Odchodzi = wszystko zablokowane. Zero ręcznego zarządzania dostępami.", savingsMin: 2, savingsMax: 4, automationPercent: 75 },
    { lp: 91, name: "Automatyczne tworzenie newsletterów z AI kuracji treści", categorySlug: "content-marketing", integrations: "HTTP/Webhook, Sheets, Mailchimp, AI", descriptionTechnical: "Generowanie spersonalizowanych newsletterów z automatyczną kuracją treści", descriptionMarketing: "Newslettery piszą się same. AI wybiera najlepsze treści i komponuje angażujące e-maile.", savingsMin: 3, savingsMax: 5, automationPercent: 75 },
    { lp: 92, name: "System automatycznego tworzenia postów do social media z RSS", categorySlug: "social-media-wideo", integrations: "HTTP/Webhook, RSS, Buffer, AI", descriptionTechnical: "Automatyczna konwersja wpisów blogowych na posty social media", descriptionMarketing: "Blog post = 5 postów social media. AI przekształca artykuły w angażujące posty dla każdej platformy.", savingsMin: 2, savingsMax: 4, automationPercent: 75 },
    { lp: 93, name: "Automatyzacja analizy hashtagów i trendów", categorySlug: "social-media-wideo", integrations: "HTTP/Webhook, Sheets, AI", descriptionTechnical: "Automatyczne śledzenie i analiza trendujących hashtagów", descriptionMarketing: "Zawsze na czasie z trendami. AI monitoruje hashtagi i sugeruje te najlepsze dla Twoich postów.", savingsMin: 1, savingsMax: 3, automationPercent: 75 },
    { lp: 94, name: "System automatycznego planowania treści sezonowych", categorySlug: "content-marketing", integrations: "HTTP/Webhook, Sheets, Google, AI", descriptionTechnical: "Automatyczne planowanie kampanii na święta i wydarzenia", descriptionMarketing: "Kampanie świąteczne zaplanowane rok do przodu. AI przypomina i generuje content na każdą okazję.", savingsMin: 2, savingsMax: 4, automationPercent: 75 },
    { lp: 95, name: "Automatyzacja zarządzania programami afiliacyjnymi", categorySlug: "lead-generation-sprzedaz", integrations: "HTTP/Webhook, Sheets, CRM", descriptionTechnical: "Automatyczne śledzenie i rozliczanie prowizji afiliacyjnych", descriptionMarketing: "Program partnerski na autopilocie. Śledzenie linków, naliczanie prowizji, wypłaty - wszystko automatycznie.", savingsMin: 3, savingsMax: 6, automationPercent: 75 },
    { lp: 96, name: "System automatycznego wykrywania i usuwania duplikatów", categorySlug: "zarzadzanie-trescia", integrations: "HTTP/Webhook, Sheets, Google Drive, AI", descriptionTechnical: "Automatyczne wykrywanie i zarządzanie zduplikowanymi plikami", descriptionMarketing: "Koniec z bałaganem w plikach. AI znajduje duplikaty i sugeruje które zachować, a które usunąć.", savingsMin: 2, savingsMax: 4, automationPercent: 75 },
    { lp: 97, name: "Automatyzacja tworzenia prezentacji z danych", categorySlug: "zarzadzanie-trescia", integrations: "HTTP/Webhook, Sheets, Google Slides, AI", descriptionTechnical: "Automatyczne generowanie prezentacji z danych źródłowych", descriptionMarketing: "Prezentacje w minuty. AI pobiera dane i tworzy profesjonalne slajdy z wykresami i wnioskami.", savingsMin: 3, savingsMax: 6, automationPercent: 75 },
    { lp: 98, name: "System automatycznego zarządzania subskrypcjami SaaS", categorySlug: "finanse-analityka", integrations: "HTTP/Webhook, Sheets, AI", descriptionTechnical: "Śledzenie i optymalizacja subskrypcji firmowych", descriptionMarketing: "Wszystkie subskrypcje w jednym miejscu. AI przypomina o odnowieniach i sugeruje oszczędności.", savingsMin: 2, savingsMax: 4, automationPercent: 75 },
    { lp: 99, name: "Automatyzacja tworzenia wideo produktowych z AI", categorySlug: "e-commerce", integrations: "HTTP/Webhook, Sheets, AI", descriptionTechnical: "Generowanie filmów produktowych na podstawie zdjęć i opisów", descriptionMarketing: "Wideo produktowe z samych zdjęć. AI animuje, dodaje muzykę i napisy. Profesjonalne filmy dla każdego produktu.", savingsMin: 4, savingsMax: 8, automationPercent: 75 },
    { lp: 100, name: "System automatycznego tagowania i organizacji zdjęć", categorySlug: "grafika-design", integrations: "HTTP/Webhook, Google Photos, AI", descriptionTechnical: "Automatyczne rozpoznawanie i tagowanie zawartości zdjęć", descriptionMarketing: "Tysiące zdjęć zorganizowanych automatycznie. AI rozpoznaje co jest na zdjęciu i taguje właściwie.", savingsMin: 2, savingsMax: 4, automationPercent: 75 },
    { lp: 101, name: "Automatyzacja tworzenia dokumentacji API", categorySlug: "it-devops", integrations: "HTTP/Webhook, GitHub, Swagger, AI", descriptionTechnical: "Automatyczne generowanie i aktualizacja dokumentacji API", descriptionMarketing: "Dokumentacja API zawsze aktualna. AI generuje ją z kodu i aktualizuje przy każdej zmianie.", savingsMin: 3, savingsMax: 6, automationPercent: 75 },
    { lp: 102, name: "System automatycznego testowania regresyjnego", categorySlug: "it-devops", integrations: "HTTP/Webhook, GitHub, Selenium, AI", descriptionTechnical: "Automatyczne uruchamianie testów regresyjnych przy zmianach kodu", descriptionMarketing: "Każda zmiana przetestowana. AI uruchamia testy i raportuje problemy przed deployem.", savingsMin: 4, savingsMax: 8, automationPercent: 75 },
    { lp: 103, name: "Automatyzacja analizy logów i wykrywania anomalii", categorySlug: "it-devops", integrations: "HTTP/Webhook, Sheets, AI", descriptionTechnical: "Inteligentna analiza logów z wykrywaniem nietypowych wzorców", descriptionMarketing: "Logi analizowane automatycznie. AI wykrywa anomalie i alarmuje zanim staną się problemem.", savingsMin: 3, savingsMax: 6, automationPercent: 75 },
    { lp: 104, name: "System automatycznego zarządzania sekretami i konfiguracją", categorySlug: "it-devops", integrations: "HTTP/Webhook, Vault, Kubernetes", descriptionTechnical: "Bezpieczne zarządzanie hasłami i konfiguracją środowisk", descriptionMarketing: "Sekrety bezpieczne i zorganizowane. Rotacja haseł, zarządzanie dostępem - wszystko automatycznie.", savingsMin: 2, savingsMax: 4, automationPercent: 75 },
    { lp: 105, name: "Automatyzacja tworzenia środowisk deweloperskich", categorySlug: "it-devops", integrations: "HTTP/Webhook, Docker, GitHub", descriptionTechnical: "Automatyczne tworzenie izolowanych środowisk dev dla każdej gałęzi", descriptionMarketing: "Każdy PR = własne środowisko testowe. Developer pushuje kod, środowisko tworzy się automatycznie.", savingsMin: 3, savingsMax: 6, automationPercent: 75 },
    { lp: 106, name: "System automatycznego powiadamiania o urodzinach klientów", categorySlug: "obsuga-klienta-crm", integrations: "HTTP/Webhook, CRM, Mailchimp", descriptionTechnical: "Automatyczne wysyłanie życzeń urodzinowych do klientów", descriptionMarketing: "Każdy klient czuje się wyjątkowo. Automatyczne życzenia urodzinowe z personalizowaną ofertą.", savingsMin: 1, savingsMax: 2, automationPercent: 75 },
    { lp: 107, name: "Automatyzacja programów lojalnościowych", categorySlug: "e-commerce", integrations: "HTTP/Webhook, Sheets, Shopify", descriptionTechnical: "Automatyczne naliczanie i zarządzanie punktami lojalnościowymi", descriptionMarketing: "Program lojalnościowy na autopilocie. Punkty naliczane, nagrody wysyłane, klienci wracają.", savingsMin: 2, savingsMax: 4, automationPercent: 75 },
    { lp: 108, name: "System automatycznego tworzenia kuponów i kodów rabatowych", categorySlug: "e-commerce", integrations: "HTTP/Webhook, Sheets, Shopify", descriptionTechnical: "Dynamiczne generowanie i dystrybucja kodów rabatowych", descriptionMarketing: "Kupony personalizowane dla każdego klienta. AI generuje unikalne kody i śledzi ich wykorzystanie.", savingsMin: 1, savingsMax: 3, automationPercent: 75 },
    { lp: 109, name: "Automatyzacja integracji z marketplace'ami", categorySlug: "e-commerce", integrations: "HTTP/Webhook, Sheets, Allegro, Amazon", descriptionTechnical: "Synchronizacja produktów i zamówień z marketplace'ami", descriptionMarketing: "Sprzedaż na Allegro, Amazon, eBay z jednego panelu. Produkty i zamówienia synchronizowane automatycznie.", savingsMin: 4, savingsMax: 8, automationPercent: 75 },
    { lp: 110, name: "System automatycznego zarządzania reklamacjami gwarancyjnymi", categorySlug: "obsuga-klienta-crm", integrations: "HTTP/Webhook, Sheets, CRM, AI", descriptionTechnical: "Automatyczna obsługa procesu reklamacji z śledzeniem statusu", descriptionMarketing: "Reklamacje obsługiwane sprawnie. System śledzi status, informuje klienta i eskaluje opóźnienia.", savingsMin: 3, savingsMax: 5, automationPercent: 75 },
    { lp: 111, name: "Automatyzacja rozliczeń prowizyjnych dla handlowców", categorySlug: "finanse-analityka", integrations: "HTTP/Webhook, Sheets, CRM, AI", descriptionTechnical: "Automatyczne obliczanie i raportowanie prowizji sprzedażowych", descriptionMarketing: "Prowizje obliczane automatycznie. Każdy handlowiec widzi swoje wyniki i zarobki w czasie rzeczywistym.", savingsMin: 3, savingsMax: 6, automationPercent: 75 },
    { lp: 112, name: "System automatycznego forecastingu sprzedaży", categorySlug: "analityka-research", integrations: "HTTP/Webhook, Sheets, CRM, AI", descriptionTechnical: "Automatyczne prognozowanie sprzedaży na podstawie danych historycznych i trendów", descriptionMarketing: "Prognozy sprzedaży oparte na danych. AI analizuje wzorce i przewiduje wyniki z dokładnością 90%+.", savingsMin: 3, savingsMax: 6, automationPercent: 75 },
    { lp: 113, name: "Automatyzacja zarządzania kampaniami influencer marketingu", categorySlug: "marketing-analityka", integrations: "HTTP/Webhook, Sheets, Instagram API, AI", descriptionTechnical: "Automatyczne śledzenie i raportowanie kampanii z influencerami", descriptionMarketing: "Influencer marketing pod kontrolą. Śledzenie postów, zaangażowania i ROI każdej współpracy.", savingsMin: 3, savingsMax: 6, automationPercent: 75 },
  ]
}

export async function GET(request: Request) {
  // Simple protection - check for setup key
  const { searchParams } = new URL(request.url)
  const key = searchParams.get('key')

  if (key !== 'ordoflow-seed-2024') {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  try {
    const payload = await getPayload({ config })

    // Check if data already exists
    const existingCategories = await payload.count({ collection: 'categories' })
    if (existingCategories.totalDocs > 0) {
      return NextResponse.json({
        success: true,
        message: 'Data already seeded',
        categories: existingCategories.totalDocs,
      })
    }

    // Create categories first
    const categoryMap: Record<string, number | string> = {}

    for (const cat of seedData.categories) {
      const created = await payload.create({
        collection: 'categories',
        data: {
          name: cat.name,
          slug: cat.slug,
          icon: cat.icon,
          displayOrder: cat.displayOrder,
          isActive: true,
        },
      })
      categoryMap[cat.slug] = created.id
    }

    // Create automations
    let automationsCreated = 0
    for (const auto of seedData.automations) {
      const categoryId = categoryMap[auto.categorySlug]
      if (categoryId) {
        await payload.create({
          collection: 'automations',
          data: {
            lp: auto.lp,
            name: auto.name,
            category: categoryId,
            integrations: auto.integrations,
            descriptionTechnical: auto.descriptionTechnical,
            descriptionMarketing: auto.descriptionMarketing,
            savingsMin: auto.savingsMin,
            savingsMax: auto.savingsMax,
            automationPercent: auto.automationPercent,
            isActive: true,
          },
        })
        automationsCreated++
      }
    }

    return NextResponse.json({
      success: true,
      message: 'Data seeded successfully',
      categories: Object.keys(categoryMap).length,
      automations: automationsCreated,
    })
  } catch (error) {
    console.error('Seed error:', error)
    return NextResponse.json({
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error'
    }, { status: 500 })
  }
}
